### ISSUE TITLE
unqualified psuedo-classes are combined with previous seletor

### ISSUE THREAD

**Issue by AaronAsAChimp** [ded/sqwish#10]
sqwish incorrectly combines pseudo-classes with the previous selector when it is unqualified.

styles.css

``` css
.class :first-child {
    color: red;
}
```

styles.min.css

``` css
.class:first-child{color:red}
```

Qualifying it with an asterisk seems to be an effective workaround. On a related thought, but not necessarily related to this bug, it could probably be removed when minifying to save a byte.
