### ISSUE TITLE
--strict and font-face optimizations

### ISSUE THREAD

**Issue by rstacruz** [ded/sqwish#12]
Looks like --strict doesn't support multiple font faces.

``` css
@font-face { font-family: 'Exo'; src: url(exo.ttf); }
@font-face { font-family: 'Exo'; src: url(exo.ttf); }
@font-face { font-family: 'Oswald'; src: url(oswald.ttf); }
```

Expected output:

``` css
@font-face{font-family:Exo;src:url(exo.ttf)}@font-face{font-family:Oswald;src:url(oswald.ttf)}
```

Actual output (v0.2.0):

``` css
@font-face{font-family:Oswald;src:url(oswald.ttf)}
```
