### ISSUE TITLE
Strict and Wildcardselector will break

### ISSUE THREAD

**Issue by ottes** [ded/sqwish#20]
input (snippet from bootstrap.css)

``` css
@media print {
  * {
    color: #000 !important;
    text-shadow: none !important;
    background: transparent !important;
    box-shadow: none !important;
  } (.....)
```

Problem:
Syntax Error: Invalid regular expression: /^*{color:/: Nothing to repeat

Solution:
return dec.match(new RegExp('^' + prop.replace(/[-\/\^$*+?.()|[]{}]/g, '\$&') + ':'));
instead of
return dec.match(new RegExp('^' + prop + ':'));
